### ISSUE TITLE
노트

### ISSUE THREAD

**Issue by Tao-Kim** [Tao-Kim/study_algo#1]
### update
group : g50
programmers : p16
baekjoon : b7

# python
### Todo
- [x] [작성중] 문제풀며 처음보는input 활용법 정리 - [링크](https://github.com/Tao-Kim/study_algo/blob/master/note/grammar/python_input%EC%A0%95%EB%A6%AC.py)
- [x] [작성중] 문제풀며 처음보는 내장함수, 라이브러리 정리하기
- [x] 파이썬 문자열 조작 정리 - 20200901 전까지 - [링크](https://github.com/Tao-Kim/study_algo/blob/master/note/grammar/python_%EB%AC%B8%EC%9E%90%EC%97%B4%EC%A1%B0%EC%9E%91.py)
- [x] 리스트 선언 총 정리 + 컴프리헨션 정리하기
- [x] 파이썬 스택, 큐, 우선순위큐 정리하기
- [ ] 파이썬 문자열에 정규식 적용하는법 있는지 찾아보기
- [ ] itertools - count(), cycle(), repeat() 찾아보기
- [x] map, filter, reduce 등 + 람다 정리하기
- [x] 파이썬 sort에 key 파라미터 찾아보기
- [x] functools.cmp_to_key 찾아보기
- [x] enumerate에 인덱스 지정 방법 찾아보기
- [x] 파이썬 any, all 함수 찾아보기
- [x] 파이썬 기본 자료구조 메소드 찾아보기
- [x] dict 찾아보기
- [x] collections.Counter 찾아보기
- [x] [https://dev.plusblog.co.kr/42 살펴보기](https://dev.plusblog.co.kr/42)
- [x] [https://wiki.python.org/moin/TimeComplexity 살펴보기](https://wiki.python.org/moin/TimeComplexity)
- [x] 파이썬 기본 문법 복습
- [x] 내장함수, 라이브러리 살펴보기
- [x] global 변수 선언하는 거 찾아보기
- [x] 파이썬 input 활용법 공부
- [x] python sort, sorted 공부
- [x] reduce, filter 공부
- [x] 리스트 컴프리헨션 공부
- [x] g4, g5 다시풀기 - 규칙 리스트로 선언해서 처리하는 식으로
- [x] g5_2 복습
- [x] g11 다시풀기
- [x] g12 다시풀기
- [x] g15 다시풀기
- [x] g18 다시풀기
- [x] g18_2 다시풀기 - 20200830
- [x] g17 다시풀기 - 다익스트라로 풀어보기
- [x] g19 수정
- [x] g19 다시풀기
- [x] g20 다시풀기
- [x] g21 다시풀기
- [x] g21_2 다시풀기 20200831
- [x] g25 다시풀기
- [x] g22, g23, g25, g26, g32 해설 한번 보기
- [x] g42 다시풀기
- [x] g50 복습
- [ ] p3 복습
- [ ] p7 다시풀기
- [ ] p13 ~ 23 복습

### Note
- 리스트 정렬시 sorted 활용하면 코드 간결해질때 있음
- i, j, k = [1, 2, 3] 방식으로 할당가능
- map에 람다 활용고려 ex - list(map(lambda , v) 
- list(map(int, input())) : 1111111111 -> [1, 1, 1, 1, 1, 1, 1, 1] 
- chr() 아스키코드로 문자 반환
- ord() 아스키코드 반환 함수
- bin() 10진수 -> 2진수
- 파이썬 map에 sum 적용 가능 : sum(map(int, ~))
- 파이썬 삼항연산자 : [true_value] if [condition] else [false_value]
- [0, 1, 2, 3] 순환하는 꼴 x = (x + 1) % 4로 처리 가능
- 파이썬 리스트 삭제 remove(요소), pop(인덱스)도 고려하기 (물론 큐보단 성능 나쁨)
- 파이썬 for 루프 인덱스 구하기 : for index, value in enumerate(iterable):

# 알고리즘
### Todo
- [ ] trie 자료구조 공부 및 작성
- [ ] dfs/bfs 문제 풀이 속도 오래걸림 많이 풀어볼 것
- [ ] DP 문제 많이 풀어보기
- [ ] 그래프 문제 풀이 속도 오래걸림 많이 풀어볼 것
- [ ] 다익스트라 문제 풀이
- [ ] 정규식 공부
- [ ] 배열곱셈 알고리즘 풀기 및 정리
- [ ] 누적합 알고리즘 공부
- [ ] 비트마스크 알고리즘 공부
- [ ] 휴리스틱 알고리즘 공부
- [x] 파리메트릭 서치 개념 찾아보기
- [x] 프로그래머스 레벨1 통과하기
- [x] 프로그래머스 레벨2 통과하기
- [x] 프로그래머스 레벨3 통과하기
- [ ] solved.ac class1 통과하기
- [ ] LeetCode Top100 풀기
- [x] goormdevth에서 작성 연습
- [x] 프로그래머스에서 작성 연습
- [ ] 해커랭크에서 작성 연습
- [x] 릿코드에서 작성 연습
- [x] 코딜리티에서 작성 연습
- [ ] 리모트인터뷰에서 작성 연습

### Note
- 인덱스에 규칙이 있다면 별도의 리스트로 지정해두고 활용하는 방법 - [참고링크](https://github.com/Tao-Kim/study_algo/blob/master/group/g5_%EA%B2%8C%EC%9E%84%EA%B0%9C%EB%B0%9C_p118.java)
- 2차원 배열 덩어리로 묶는 문제 dfs/bfs 풀이로 접근하면 편함
- 가중치를 두며 완전 탐색할때 bfs로 접근하면 가중치 처리가 더 편함 - [참고링크](https://github.com/Tao-Kim/study_algo/blob/master/group/g7_%EB%AF%B8%EB%A1%9C%ED%83%88%EC%B6%9C_p152.py)
- 탐색문제 연산량 추정해서 logn(이진탐색) 여부 파악해야 함
- 탐색문제 조건 확인후 set, 계수정렬 활용여부 파악해야 함 - [참고링크](https://github.com/Tao-Kim/study_algo/blob/master/group/g11_%EB%B6%80%ED%92%88%EC%B0%BE%EA%B8%B0_p197.py)
- 점화식 찾을때 바텀업 뿐만아니라 탑다운으로도 생각해보기
- 로직이 복잡한 경우 함수로 나누기
- 입력 범위가 작고, 로직이 복잡한 경우 구현 문제인지 생각해보기
- 문제를 꼼꼼히 읽고 코드도 꼼꼼히 작성할 것 디버깅에서 시간 더걸림
- 테스트 케이스를 미리 추가하는 습관 필요
- DP 점화식 수학으로 생각해보기
- goorm 입출력 직접 코딩, 출력 예민함 띄어쓰기까지 신경써야함
