### ISSUE TITLE
노트 java분리

### ISSUE THREAD

**Issue by Tao-Kim** [Tao-Kim/study_algo#2]
# java
### Todo
- [x] 자바 기본 문법 복습
- [x] utils 살펴보기
- [x] 자바 문자열 조작 문법 살펴보기
- [x] comparable, comparator 비교해보기
- [x] 자바 내림차순 정렬 조사하기
- [x] nextInt() nextInt() 후 줄 바뀌고 nextLine()으로 입력시 에러 원인 찾기(버퍼 예상됨)
- [x] 자바에서 큐로 bfs하는법 공부
- [x] Math 찾아보기
- [ ] 자바 배열 조작 정리
- [ ] 자바 출력함수 정리하기
- [ ] 자바 각 컬렉션, 이터러블 정리하고 정렬 조사하기
- [ ] 자바 utils 정리하기
- [ ] 자바 스택, 큐, 우선순위큐 정리하기
- [ ] java 입력 정리하기
- [ ] java stream 정리하기

### Note
- 반복문에서 index 필요할때 기본 for문이 더 편할수도 있음
- string.charAt() : 문자열의 특정 인덱스의 char 구하기
- char - '0' : char to int
- 110101 과 같이 붙어있는 input 처리법 : String line 입력후 반복문으로 charAt 나누기
- nextInt() 는 입력 마지막 개행문자 처리안함
